-- 1. Run this in your Supabase SQL Editor

-- Create applications table
create table if not exists applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text check (type in ('company', 'visa')) not null,
  status text check (status in ('pending', 'processing', 'completed')) default 'pending',
  data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table applications enable row level security;

-- Policies for applications
create policy "Users can view their own applications"
  on applications for select
  using (auth.uid() = user_id);

create policy "Users can insert their own applications"
  on applications for insert
  with check (auth.uid() = user_id);

-- Note: Admins (Service Role) bypass RLS automatically.

-- 2. Storage Setup
-- Go to Supabase Dashboard -> Storage -> Create a new bucket named 'ifza-documents'.
-- Make sure it is NOT a public bucket (unless you want public access, but usually these are private).

-- Then run these policies for Storage:

create policy "Users can upload their own documents"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'ifza-documents' and
  (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can view their own documents"
on storage.objects for select
to authenticated
using (
  bucket_id = 'ifza-documents' and
  (storage.foldername(name))[1] = auth.uid()::text
);
